#!/usr/bin/env php
<?php
require_once './vendor/autoload.php';

if(sizeof($argv) > 1)
{
    $allowedTypes = ['glorf', 'flub'];
    if(in_array($argv[1], $allowedTypes))
    {
        try{
            $videoImport = new \App\controllers\VideoImport();
            $videoImport->import($argv[1]);
        }
        catch(Exception $e)
        {
            echo "Error: ". $e->getMessage() . "\n";
        }
        exit(1);
    }
    else if($argv[1] === 'h' || $argv[1] === 'help')
    {
        echo "\nUsage example:\n\n ./import {{option}}\n\n
        Options:\n
        glorf : Import videos from glorf source\n
        flub : Import videos from flub source\n\n
        Import videos from glorf source:\n
        ./import glorf\n\n";
        exit(1);
    }
    else
    {
        echo "Wrong argument\nTry executing with \"help\" or \"h\" argument to see available options.\n";
        exit(1);
    }
}
else
{
    echo "Argument is Required to import videos\nTry executing with \"help\" or \"h\" argument to see available options.\n";
    exit(1);
}



